services:
  api:
    image: csc131/transit
    container_name: transit-api
    build: .
    environment:
        - spring.profiles.active=test   
    depends_on:
      - db    
    ports:
      - "8080:8080"
  db:
    image: mongo
    container_name: transit-db
    restart: always
    ports:
      - "27017:27017" 
      

